setup path

diff --git a/src/utils/installers/bash b/src/utils/installers/bash
--- a/src/utils/installers/bash
+++ b/src/utils/installers/bash
@@ -8,6 +8,8 @@ function install() {
     compile "$src" "$dist" "$properties"
 
     postInstall
+
+    add_to_path "$dist"
 }
 
 function postInstall() {
@@ -61,4 +63,14 @@ function compile() {
             "__ROOT__/utils/compiler" "$file" "$fileC" "$properties"
         fi
     done
+}
+
+function add_to_path() {
+	local dist="$1"
+	local project_name=`basename $PWD`
+	main=`getConfig "main" "$project_name"`
+	main_file="$dist/$main"
+
+	test -f "$main_file" || error "File $main_file not found"
+	ln -s "$main_file" "$WX_PATH/$main"
 }
